data:
  train_path: "/media/francesco/STORAGE/Coll_2V_VBFHbb_preliminary_prove/Train"
  val_path: "/media/francesco/STORAGE/Coll_2V_VBFHbb_preliminary_prove/Val"
  test_path: "/media/francesco/STORAGE/Coll_2V_VBFHbb_preliminary_prove/Test"
  batch_size: 32
  features: 
    - L1T_PUPPIPart_Eta 
    - L1T_PUPPIPart_Phi
    - L1T_PUPPIPart_PT
    - L1T_PUPPIPart_PID
    - L1T_PUPPIPart_PuppiW
  jet_features:
    - L1T_JetPuppiAK4_PT
    - L1T_JetPuppiAK4_Eta
    - L1T_JetPuppiAK4_Phi
    - L1T_JetPuppiAK4_Mass
    - L1T_JetPuppiAK8_PT
    - L1T_JetPuppiAK8_Eta
    - L1T_JetPuppiAK8_Phi
    - L1T_JetPuppiAK8_Mass

model:
  input_dim: 3
  hidden_dim: 128
  latent_dim: 256
  codebook_size: 256
  rotation_trick: true

training:
  batch_size: 32
  lr: 0.001
  weight_decay: 0.0001
  max_epochs: 50
  precision: 16

VQVAE:
  beta: 0.25
